
# STAT 109 — Lab 2 Assignment

**Purpose:** In this lab we introduce beginner-friendly **data structures in R** (vectors and matrices) and get more practice writing **for loops**. We also connect probability ideas to **simulation** when the sample space has **equally likely outcomes**.


------------------------------------------------------------------------

## Learning goals (what students should be able to do after Lab 2)

- Identify common R **types**: numeric, integer, character, logical
- Create and work with **vectors**: `c()`, indexing with `[ ]`, logical comparisons and filtering
- Write a basic **for loop** that stores results
- Use simulation to estimate probabilities for **equally likely outcomes**



------------------------------------------------------------------------

## Part 1 — Data types (what kind of thing is this?)

In R, every value has a **type**. You don’t have to memorize these right away—just know how to *check* the type when you’re unsure.

-   **numeric**: numbers that can include decimals (e.g. `3.14`)
-   **integer**: whole numbers (e.g. `3L` — the `L` means “integer”)
-   **character**: text/strings (e.g. `"STAT 109"`)
-   **logical**: `TRUE` / `FALSE` (often from comparisons like `3 < 5`)

Two helpful functions:

- `class(x)` tells you the “kind of thing” R thinks `x` is.
- `typeof(x)` is a lower-level type label (don’t worry about small differences yet).

### 1.1 Check the type of a number

**Goal output**



In [ ]:
[1] "numeric"



**Your task:** Store `3.5` in `x` and check its class.



In [ ]:
# Solution




------------------------------------------------------------------------

### 1.2 Integer vs numeric

**Goal output**



In [ ]:
[1] "integer"



**Your task:** Store an integer in `y` and check its class.



In [ ]:
# Solution




------------------------------------------------------------------------

### 1.3 Character (string) values use quotes

**Goal output**



In [ ]:
[1] "character"



**Your task:** Store `"hello"` in `w` and check its class.



In [ ]:
# Solution




------------------------------------------------------------------------

### 1.4 Logical values come from comparisons

**Goal output**



In [ ]:
[1] TRUE



**Your task:** Write a comparison that evaluates to `TRUE`.



In [ ]:
# Solution (one possible answer)




------------------------------------------------------------------------

### 1.5 Converting (coercing) types

Sometimes you have `"7"` (text) but you need `7` (a number).

**Goal output**



In [ ]:
[1] 7



**Your task:** Convert the character `"7"` into a numeric value.



In [ ]:
# Solution




**Note:** `as.numeric("seven")` gives `NA` (missing) because R can’t turn the word “seven” into a number.

------------------------------------------------------------------------

## Part 2 — Vectors (the basic data structure)

### 2.1 Create a numeric vector

**Goal output**



In [ ]:
[1] 2 4 6 8 10



**Your task:** Create a vector named `numbers` containing `2, 4, 6, 8, 10`.



In [ ]:
# Solution




------------------------------------------------------------------------

### 2.2 Create a character vector

**Goal output**



In [ ]:
[1] "H" "T" "H" "H" "T"



**Your task:** Create a vector named `flips` containing `"H", "T", "H", "H", "T"`.



In [ ]:
# Solution




------------------------------------------------------------------------

### 2.3 Sequences and repetition

**Goal output**



In [ ]:
[1] 1 2 3 4 5 6



**Your task:** Create the sequence 1 through 6 without typing every number.



In [ ]:
# Solution




------------------------------------------------------------------------

### 2.3b Check the “size” of a vector with `length()`

Many errors come from combining objects of different sizes. For vectors, the size is the **length** (how many entries).

**Goal output**



In [ ]:
[1] 5



**Your task:** Check the length of `numbers <- c(2, 4, 6, 8, 10)`.



In [ ]:
# Solution
numbers <- c(2, 4, 6, 8, 10)




------------------------------------------------------------------------

### 2.3c Combine two vectors of the same length (element-by-element)

When two vectors have the same length, `+` and `==` work **element-by-element**.

**Goal output**



In [ ]:
[1] 11 22 33



**Your task:** Add the vectors `a <- c(1, 2, 3)` and `b <- c(10, 20, 30)`.



In [ ]:
# Solution
a <- c(1, 2, 3)
b <- c(10, 20, 30)




**Diagnostic tip:** If `length(a) != length(b)`, stop and fix that first.

------------------------------------------------------------------------

### 2.3d Add or multiply a vector by a single number (a “scalar”)

Adding or multiplying by a single number applies to **every entry** of the vector.

**Goal output**



In [ ]:
[1] 7 9 11



**Your task:** Start with `v <- c(2, 4, 6)` and create `v_plus_5 <- v + 5`.



In [ ]:
# Solution
v <- c(2, 4, 6)




**Also useful:**



In [ ]:
# multiply every entry by 2
# Solution
v <- c(2, 4, 6)



------------------------------------------------------------------------

### 2.4 Indexing and subsetting

Run the code below. What does `numbers[3]` return?



In [ ]:
numbers <- c(2, 4, 6, 8, 10)
numbers[3]



**Solution:** `numbers[3]` returns ...

------------------------------------------------------------------------

### 2.4b Bracketing practice (vectors)

The brackets `[...]` are one of the most important skills in R. Here are common patterns you’ll use all semester.

Use this setup:



In [ ]:
numbers <- c(2, 4, 6, 8, 10)



**2.4b(i) Grab multiple positions**

**Goal output**



In [ ]:
[1] 2 6 10



**Your task:** Use brackets to grab the 1st, 3rd, and 5th entries.



In [ ]:
# Solution




------------------------------------------------------------------------

**2.4b(ii) Grab a range of positions**

**Goal output**



In [ ]:
[1] 4 6 8



**Your task:** Use brackets to grab the 2nd through 4th entries.



In [ ]:
# Solution




------------------------------------------------------------------------

**2.4b(iii) Drop a position (negative index)**

**Goal output**



In [ ]:
[1] 2 4 8 10



**Your task:** Use brackets to return everything **except** the 3rd entry.



In [ ]:
# Solution




------------------------------------------------------------------------

**2.4b(iv) Use a logical vector inside brackets**

**Goal output**



In [ ]:
[1] 6 8 10



**Your task:** Use a condition inside brackets to keep values greater than 5.



In [ ]:
# Solution




------------------------------------------------------------------------

### 2.5 Logical conditions create TRUE/FALSE vectors

**Goal output**



In [ ]:
[1] FALSE FALSE  TRUE  TRUE  TRUE



**Your task:** Create a logical vector that checks which entries of `numbers` are greater than 5.



In [ ]:
# Solution
numbers <- c(2, 4, 6, 8, 10)




------------------------------------------------------------------------

### 2.6 Logical subsetting (filtering)

**Goal output**



In [ ]:
[1] 6 8 10



**Your task:** Use logical subsetting to keep only the values in `numbers` that are greater than 5.



In [ ]:
# Solution
numbers <- c(2, 4, 6, 8, 10)




------------------------------------------------------------------------

## Part 3 — Matrices (2D numeric data)

Matrices are a 2D extension of vectors. The key idea is the same brackets, but now you give **row** and **column**: `m[row, col]`.

### 3.1 Create a matrix and index it

**Goal output**



In [ ]:
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6



**Your task:** Create a 2x3 matrix with the numbers 1 through 6 filled **by column**.



In [ ]:
# Solution
m = # your matrix creation code here
m




------------------------------------------------------------------------

### 3.1b Check the “size” of a matrix with `dim()`, `nrow()`, `ncol()`

For matrices, the size is **rows and columns**.

**Goal output**



In [ ]:
[1] 2 3



**Your task:** Check the dimensions of `m`.



In [ ]:
# Solution




**Also useful (one number at a time):**



In [ ]:
nrow(m)
ncol(m)



------------------------------------------------------------------------

### 3.1c Combine two matrices of the same size (element-by-element)

If two matrices have the same dimensions, `+` and `==` work element-by-element (this is **not** matrix multiplication).

**Goal output**



In [ ]:
     [,1] [,2] [,3]
[1,]    2    6   10
[2,]    4    8   12



**Your task:** Create `m2 <- m` and compute `m + m2`.



In [ ]:
# Solution




**Diagnostic tip:** If `dim(m) != dim(m2)`, you cannot add them safely.

------------------------------------------------------------------------

### 3.1d Add or multiply a matrix by a single number (a “scalar”)

Just like vectors, a single number applies to every entry.

**Goal output**



In [ ]:
     [,1] [,2] [,3]
[1,]    6    8   10
[2,]    7    9   11



**Your task:** Compute `m + 5`.



In [ ]:
# Solution




**Also useful:**



In [ ]:
2 * m
m * 2



------------------------------------------------------------------------

### 3.2 Extract a row and a column

**Goal output**



In [ ]:
[1] 1 3 5



**Your task:** Extract the first row of `m`.



In [ ]:
# Solution




------------------------------------------------------------------------

### 3.3 Bracketing practice (matrices)

Use this setup (same `m` as above):



In [ ]:
m <- matrix(1:6, nrow = 2, ncol = 3)
m



**3.3(i) One entry (row, column)**

**Goal output**



In [ ]:
[1] 4



**Your task:** Extract the entry in row 2, column 2.



In [ ]:
# Solution




------------------------------------------------------------------------

**3.3(ii) One column**

**Goal output**



In [ ]:
[1] 3 4



**Your task:** Extract the 2nd column of `m`.



In [ ]:
# Solution




------------------------------------------------------------------------

**3.3(iii) A submatrix (multiple rows and columns)**

**Goal output**



In [ ]:
     [,1] [,2]
[1,]    1    3
[2,]    2    4



**Your task:** Extract rows 1:2 and columns 1:2.



In [ ]:
# Solution




------------------------------------------------------------------------

## Part 4 — For loops (repeat a process and store results)

### 4.0 Anatomy of a `for` loop (what each piece means)

A `for` loop repeats the same steps many times. Here is the basic “shape”:



In [ ]:
for (i in 1:n) {
  # code to repeat goes here
}



What the parts mean:

- `for (...) { ... }`: tells R “repeat what’s inside the braces `{}`”.
- `i`: the **index variable** (a name you choose). It takes on values one-at-a-time.
- `in 1:n`: the **sequence** of values `i` will go through (here: 1, 2, 3, ..., n).
- `{` and `}`: the braces mark the **body** of the loop (the code that repeats).

Most of the time we also:

- **Pre-allocate storage** (make an empty vector first) so we have a place to save results.
- **Store one result each time** using indexing like `results[i] <- ...`.

#### Making “empty placeholders” (pre-allocation)

When you know you will store **n numbers**, it helps to create the container first:

- `numeric(n)` makes a vector of length `n` filled with zeros (a placeholder for numbers).
- `logical(n)` makes a vector of length `n` filled with `FALSE`.
- `character(n)` makes a vector of length `n` filled with `""` (empty strings).

For matrices, you can do the same idea in 2D:

- `matrix(NA, nrow = r, ncol = c)` makes an `r` by `c` placeholder matrix.

### 4.1 A simple for loop over 1 to 5

**Goal output**



In [ ]:
[1]  1  4  9 16 25



**Your task:** Use a `for` loop to fill a vector with the squares of 1 through 5.



In [ ]:
# Solution
results <- numeric(5) # storage: 5 empty slots
for (i in 1:5) {
  # i takes values 1, 2, 3, 4, 5
  results[i] <-#  fill in this bit
}
results


[1]  1  4  9 16 25


------------------------------------------------------------------------

### 4.2 Loop over the entries of a vector

**Goal output**



In [ ]:
[1] 3 5 7 9



**Your task:** Using a `for` loop, add 1 to each entry of `c(2, 4, 6, 8)` and store the result.



In [ ]:
# Solution
v <- c(2, 4, 6, 8)
v_plus_one <- numeric(length(v))
for (i in 1:length(v)) {
  # i runs over positions 1, 2, 3, 4
  v_plus_one[i] <- # fill in this bit
}
v_plus_one



------------------------------------------------------------------------

### 4.3 Nested loops (optional extension)

**Optional / not required for completion credit.** If students finish early, this is a good stretch problem.

**Goal output**



In [ ]:
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    2    4    6
[3,]    3    6    9



**Your task:** Use nested loops to create a 3x3 multiplication table where entry $(i,j)$ is $i \times j$.



In [ ]:
# Solution
tab <- matrix(NA, nrow = 3, ncol = 3)
for (i in 1:3) {
  for (j in 1:3) {
    tab[i, j] <- i * j
  }
}
tab



------------------------------------------------------------------------

## Part 5 — Probability and simulation (equally likely sample spaces)

Key simulation idea for easy grading:

- Make an **event** into a TRUE/FALSE statement (e.g., “roll is even”).
- The **estimated probability** is just the **proportion of TRUE values**:
  - in R: `mean(event_is_true)` works because `TRUE` counts as 1 and `FALSE` counts as 0.

### 5.1 Equally likely outcomes: one fair die

Let $S = \{1,2,3,4,5,6\}$ be the sample space for a fair die roll (all outcomes equally likely).

**New operator:** `%in%` means “is this value in this set/vector?”

- `x == 2` checks “is x equal to 2?”
- `x %in% c(2, 4, 6)` checks “is x one of 2, 4, or 6?”

For vectors, `%in%` works element-by-element and returns a TRUE/FALSE vector (just like `==` did in Lab 1).

**Your task:**
- Simulate 10,000 fair die rolls.
- Estimate $P(\text{roll is even})$.



In [ ]:
# Solution
set.seed(109)

n <- 10000
rolls <- sample(1:6, size = n, replace = TRUE)
# replace = TRUE means outcomes can repeat (like real die rolls)

p_even <- # fill in this bit
p_even



**Check (theory):** The even outcomes are {2,4,6}, so $P(\text{even}) = 3/6 = 0.5$.

------------------------------------------------------------------------

### 5.2 Two fair dice: probability the sum is 7

**Your task:**
- Simulate 50,000 pairs of fair die rolls.
- Estimate $P(\text{sum} = 7)$.



In [ ]:
# Solution
set.seed(109)

n <- 50000
# sample(..., size = n, replace = TRUE) gives n independent rolls
d1 <- sample(1:6, size = n, replace = TRUE)
d2 <- sample(1:6, size = n, replace = TRUE)

sums <- d1 + d2
p_sum7 <- # fill in this bit
p_sum7



**Check (theory idea):** There are 36 equally likely ordered pairs $(d1,d2)$. Six of them sum to 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1), so $P(\text{sum}=7) = 6/36 = 1/6$.

------------------------------------------------------------------------

### 5.3 Using a for loop to simulate many trials

**Your task:** Repeat the “sum of two dice” experiment using a `for` loop that stores each sum in a vector, then estimate $P(\text{sum}=7)$ using `mean()`.



In [ ]:
# Solution
set.seed(109)

n <- 20000
sums <- numeric(n)

for (i in 1:n) {
  # fill in this bit
}

mean(sums == 7)



------------------------------------------------------------------------

## Part 6 — Reflection (to submit in Canvas)

Write \~200–300 words total answering the prompts below.

1.  What’s the difference between a **vector** and a **matrix**? Give one sentence for each.\
2.  What bit of code was the hardest to figure out for you?  
3.  In your own words, how does simulation connect to probability when outcomes are “equally likely”?
4. Were there bits of code you couldn't figure out in this lab?  
